#!/usr/bin/env python3
"""renamr — safe batch file renaming with regex, dry-run by default.

Renames files by applying a Python regex substitution to each filename.
Nothing is touched unless you pass --apply. Detects collisions (two files
mapping to the same target, or a target that already exists) and refuses
to proceed. Can emit an undo script so any rename is reversible.

Examples:
    renamr.py 'IMG_(\\d+)' 'photo_\\1' *.jpg          # preview only
    renamr.py --apply ' ' '_' *.txt                   # spaces -> underscores
    renamr.py --apply --undo-script undo.sh '\\.jpeg$' '.jpg' *.jpeg
    renamr.py --lower '.*' - *.TXT                    # lowercase names ('-' = keep match)
"""
import argparse
import os
import re
import sys

EXIT_OK = 0
EXIT_NOTHING = 1
EXIT_COLLISION = 2
EXIT_ERROR = 3


def build_parser():
    p = argparse.ArgumentParser(
        prog="renamr",
        description="Safe batch rename with regex. Dry-run by default; "
                    "use --apply to actually rename.",
        epilog="Exit codes: 0 renamed/preview ok, 1 nothing matched, "
               "2 collision detected, 3 error.",
    )
    p.add_argument("pattern", help="Python regex applied to the filename (not the path)")
    p.add_argument("replacement",
                   help=r"replacement text; \1..\9 backrefs allowed; "
                        "use '-' to keep the name unchanged (useful with --lower/--upper)")
    p.add_argument("files", nargs="+", help="files to consider (shell globs expand naturally)")
    p.add_argument("--apply", action="store_true",
                   help="actually rename (default is a dry-run preview)")
    p.add_argument("--lower", action="store_true", help="lowercase the resulting filename")
    p.add_argument("--upper", action="store_true", help="uppercase the resulting filename")
    p.add_argument("--undo-script", metavar="PATH",
                   help="write a shell script that reverses the renames")
    p.add_argument("-q", "--quiet", action="store_true", help="suppress per-file output")
    return p


def plan_renames(args):
    """Return (plan, skipped) where plan is a list of (src, dst) with dst != src."""
    try:
        rx = re.compile(args.pattern)
    except re.error as e:
        print(f"renamr: invalid regex: {e}", file=sys.stderr)
        sys.exit(EXIT_ERROR)

    plan = []
    for src in args.files:
        if not os.path.lexists(src):
            print(f"renamr: skipping missing file: {src}", file=sys.stderr)
            continue
        d, name = os.path.split(src)
        if args.replacement == "-":
            new = name
            if not rx.search(name):
                continue
        else:
            new, n = rx.subn(args.replacement, name)
            if n == 0:
                continue
        if args.lower:
            new = new.lower()
        if args.upper:
            new = new.upper()
        if not new:
            print(f"renamr: refusing empty target name for: {src}", file=sys.stderr)
            sys.exit(EXIT_ERROR)
        if os.sep in new or (os.altsep and os.altsep in new):
            print(f"renamr: replacement may not introduce path separators: {new!r}",
                  file=sys.stderr)
            sys.exit(EXIT_ERROR)
        dst = os.path.join(d, new)
        if dst != src:
            plan.append((src, dst))
    return plan


def check_collisions(plan):
    """Return a list of human-readable collision problems."""
    problems = []
    seen = {}
    sources = {s for s, _ in plan}
    for src, dst in plan:
        if dst in seen:
            problems.append(f"both {seen[dst]!r} and {src!r} -> {dst!r}")
        seen[dst] = src
        if os.path.lexists(dst) and dst not in sources:
            problems.append(f"target already exists: {src!r} -> {dst!r}")
    return problems


def shell_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"


def write_undo(path, plan):
    with open(path, "w") as f:
        f.write("#!/bin/sh\n# generated by renamr — reverses the last rename batch\nset -e\n")
        for src, dst in reversed(plan):
            f.write(f"mv {shell_quote(dst)} {shell_quote(src)}\n")
    os.chmod(path, 0o755)


def main(argv=None):
    args = build_parser().parse_args(argv)
    plan = plan_renames(args)

    if not plan:
        if not args.quiet:
            print("renamr: no files matched the pattern (nothing to do)")
        return EXIT_NOTHING

    problems = check_collisions(plan)
    if problems:
        print("renamr: refusing to continue, collisions detected:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return EXIT_COLLISION

    for src, dst in plan:
        if not args.quiet:
            marker = "" if args.apply else " (dry-run)"
            print(f"{src} -> {dst}{marker}")
        if args.apply:
            os.rename(src, dst)

    if args.apply and args.undo_script:
        write_undo(args.undo_script, plan)
        if not args.quiet:
            print(f"renamr: undo script written to {args.undo_script}")

    if not args.apply and not args.quiet:
        print(f"renamr: {len(plan)} rename(s) previewed. Re-run with --apply to execute.")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
