import fs from 'fs';
import path from 'path';
import ignorePackage from 'ignore';

export function mapCommand() {
  console.log('🗺️  Mapping context architecture...');

  let contextMap = '# Repository Architecture Context\n\n';
  contextMap += 'This map is auto-generated by Tether. Use it to understand the file structure without blowing up context windows.\n\n';
  contextMap += '## Directory Tree\n```text\n';

  const ignore = ignorePackage.default ? ignorePackage.default : ignorePackage;
  const ig = ignore();
  
  if (fs.existsSync('.gitignore')) {
    ig.add(fs.readFileSync('.gitignore', 'utf-8'));
  }

  function walkDir(dir, depth = 0) {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (e) {
      console.error(`Warning: Skipping directory due to error: ${e.message}`);
      return;
    }

    entries.sort((a, b) => a.name.localeCompare(b.name));

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relativePath = path.relative('.', fullPath).split(path.sep).join('/');

      // Ignore hidden directories like .git
      if (entry.isDirectory() && entry.name.startsWith('.')) {
        continue;
      }

      // Respect .gitignore rules
      if (ig.ignores(relativePath + (entry.isDirectory() ? '/' : ''))) {
        continue;
      }

      const indent = '  '.repeat(depth);
      contextMap += `${indent}├── ${entry.name}\n`;

      if (entry.isDirectory()) {
        walkDir(fullPath, depth + 1);
      }
    }
  }

  walkDir('.');

  contextMap += '```\n';

  fs.writeFileSync('.agent-context.md', contextMap, 'utf-8');
  console.log('✅ Context map written to .agent-context.md');
}
